Get wiki information from new Allura wiki on SourceForge
The wiki has been moved from Trac to the new Allura platform on
SourceForge. This turns out to be much easier to download and display to
users as they can just read the markdown and I can convert most of it
using stock libraries.

diff --git a/continuous_integration/build_release b/continuous_integration/build_release
--- a/continuous_integration/build_release
+++ b/continuous_integration/build_release
@@ -11,15 +11,17 @@ if [ -z "${WORKSPACE}" ]; then
     fatal "WORKSPACE not defined, cannot continue"
 fi
 
-cd "${WORKSPACE}"
+fllsw_root="${mydir}"/..
+
+cd "${fllsw_root}"
 
 #clean up from previous run
 git clean -xdf || fatal "Error cleaning workspace"
 
-cd scoring
 
 # get wiki documentation
-./get-wiki || fatal "Error getting wiki documentation"
+cd "${fllsw_root}"/scoring/web/wiki
+../scripts/pull-wiki.py || fatal "Error getting wiki documentation"
 
+cd "${fllsw_root}"/scoring
 ./ant.sh dist || fatal "Error building distribution"
-
