Convert github markdown documentation to HTML
This removes the need to pull from the wiki on SourceForge.

diff --git a/continuous_integration/build_release b/continuous_integration/build_release
--- a/continuous_integration/build_release
+++ b/continuous_integration/build_release
@@ -26,10 +26,11 @@ if [ -n "${DEVEL_BUILD}" ]; then
     fi
 fi
 
-# get wiki documentation
-cd "${fllsw_root}"/scoring/web/wiki
-../../scripts/pull-wiki.py || fatal "Error getting wiki documentation"
-
 cd "${fllsw_root}"/scoring
 ./ant.sh dist || fatal "Error building distribution"
+
+# get wiki documentation
+cd "${fllsw_root}"/scoring/dist/tomcat/webaps/fll-sw/wiki
+"${fllsw_root}"/scoring/scripts/markdown-to-html.py *.md \
+    || fatal "Error converting wiki documentation"
 
