Add git branch to the build output

diff --git a/continuous_integration/standard_build b/continuous_integration/standard_build
--- a/continuous_integration/standard_build
+++ b/continuous_integration/standard_build
@@ -1,4 +1,11 @@
-#!/bin/bash -ex
+#!/bin/sh
+
+debug() { ! "${log_debug-false}" || log "DEBUG: $*" >&2; }
+log() { printf '%s\n' "$*"; }
+warn() { log "WARNING: $*" >&2; }
+error() { log "ERROR: $*" >&2; }
+fatal() { error "$*"; exit 1; }
+mydir=$(cd "$(dirname "$0")" && pwd -L) || fatal "Unable to determine script directory"
 
 if [ -z "${WORKSPACE}" ]; then
     echo "WORKSPACE not defined, cannot continue"
@@ -7,7 +14,10 @@ fi
 cd "${WORKSPACE}"
 
 #clean up from previous run
-git clean -xdf
+git clean -xdf || fatal "Unable to clean workspace"
+
+branch=$(git branch | grep '*' | awk -F'* ' '{print $2}') || fatal "Unable to get branch name"
+log "Building branch ${branch}"
 
 cd scoring
 ./ant.sh continuous
